-- 00_database_and_schemas.sql
-- Bootstraps the development database and logical schemas.

CREATE DATABASE IF NOT EXISTS FOOTBALL_NARRATIVE_DEV;
USE DATABASE FOOTBALL_NARRATIVE_DEV;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS OPS;
CREATE SCHEMA IF NOT EXISTS CORE;
CREATE SCHEMA IF NOT EXISTS ML;
CREATE SCHEMA IF NOT EXISTS MARTS;
