ALTER TABLE FOOTBALL_NARRATIVE_DEV.OPS.FACT_API_REQUEST ALTER COLUMN PAGE_TOKEN_USED SET DATA TYPE VARCHAR(1024);
ALTER TABLE FOOTBALL_NARRATIVE_DEV.OPS.FACT_API_REQUEST ALTER COLUMN NEXT_PAGE_TOKEN_RETURNED SET DATA TYPE VARCHAR(1024);
ALTER TABLE FOOTBALL_NARRATIVE_DEV.OPS.CURRENT_CHECKPOINT ALTER COLUMN CONTINUATION_TOKEN_HINT SET DATA TYPE VARCHAR(1024);
ALTER TABLE FOOTBALL_NARRATIVE_DEV.OPS.CHECKPOINT_HISTORY ALTER COLUMN CONTINUATION_TOKEN_HINT SET DATA TYPE VARCHAR(1024);
ALTER TABLE FOOTBALL_NARRATIVE_DEV.RAW.YOUTUBE_API_RESPONSE ALTER COLUMN PAGE_TOKEN_USED SET DATA TYPE VARCHAR(1024);
ALTER TABLE FOOTBALL_NARRATIVE_DEV.RAW.YOUTUBE_API_RESPONSE ALTER COLUMN NEXT_PAGE_TOKEN_RETURNED SET DATA TYPE VARCHAR(1024);
