ALTER TABLE FOOTBALL_NARRATIVE_DEV.CORE.BRIDGE_VIDEO_EVENT ADD COLUMN primary_exclusion_reason VARCHAR(128);
ALTER TABLE FOOTBALL_NARRATIVE_DEV.CORE.BRIDGE_VIDEO_EVENT ADD COLUMN discovery_method VARCHAR(64);
ALTER TABLE FOOTBALL_NARRATIVE_DEV.CORE.BRIDGE_VIDEO_EVENT ADD COLUMN discovery_provenance VARIANT;
