ALTER TABLE FOOTBALL_NARRATIVE_DEV.CORE.BRIDGE_VIDEO_EVENT ADD COLUMN IF NOT EXISTS primary_exclusion_reason VARCHAR(128);
ALTER TABLE FOOTBALL_NARRATIVE_DEV.CORE.BRIDGE_VIDEO_EVENT ADD COLUMN IF NOT EXISTS discovery_method VARCHAR(64);
ALTER TABLE FOOTBALL_NARRATIVE_DEV.CORE.BRIDGE_VIDEO_EVENT ADD COLUMN IF NOT EXISTS discovery_provenance VARIANT;

